### ISSUE TITLE
All of New York State is mapping to New York City

### ISSUE THREAD

**Issue by megcheese** [charlesvestal/morethanvotes#1]
New York is a very large state with more cities than just New York City.  I searched my Pleasantville, NY zipcode (10570) which is located in Westchester, NY with the "city" radio button selected I was redirected to the New York City Council.  As I am not a NYC resident, these town meetings and their topics are outside of my local interests and would not affect my neighborhood.  Pleasantville does have their own village hall and meetings.  http://www.pleasantville-ny.gov/Public_Documents/pleasantvilleny_mayor/index 

Next I tried 14150 which is the zip code for the Town of Tonawanda, NY.  Tonawanda is located in western New York outside of Buffalo.  Again, I was redirected to the New York City Council page.  Tonawanda has their own town board  with meetings; suggesting that a Tonawanda resident commute to NYC council meetings is not a useful solution.  http://www.tonawanda.ny.us/ 

Next I tried a zip code contained within the city of Buffalo, thinking that because Buffalo is a city and not a town or village it might work.  14213 still redirects to the NYC council page.  

I think your "city" feature needs to cover towns and villages too.  It also needs to recognize that everything outside the five boroughs of New York is covered by their own local governments.

**Comment by charlesvestal** [comment]
Thanks! Yes, the search query needs some tweaking and likely some overrides as well. I'll look into the best ways to account for theee cases and let you know. I appreciate the test zip codes!

**Comment by charlesvestal** [comment]
Updated the search query to `city + " " + state  + " " + 
        "(City | Village | Township)  Council Calendar " + fullstate + " Agenda";` which should give better specificity. Thanks again!
